package rules.interest.Calculate.Calculate

import com.vsp.arch.data.types.Currency;
import com.vsp.enterprise.busobj.entity.claim.PhysicianInvoice;
import com.vsp.enterprise.busobj.entity.claim.ClaimBenefitRequest;
import com.vsp.enterprise.busobj.entity.claim.PlaceOfService;
import com.vsp.enterprise.busobjsupport.interest.rule.InterestRuleContext;

rule "CLM02050" 
	no-loop
	
    when
        $pi: PhysicianInvoice($daysLate: this.getDaysPaidLate(), $daysLate > 30, $paidDate: this.getPaidDate())
        $ir: InterestRuleContext(isRuleEffective($paidDate))
  		PlaceOfService(Address.State.Idaho)
  		ClaimBenefitRequest(!GroupPopulationCode.Medicare)
  		
    then
        $ir.setPenaltyInterest(new Double(0.03288f),$daysLate,30,new Currency("4.00"),$pi);

end

